### ISSUE TITLE
using the input Trim directive disables all other custom validations applied on the control

### ISSUE THREAD

**Issue by xpgupta** [anein/angular2-trim-directive#10]

**Comment by anein** [comment]
Hi!
To understand  more precisely what is going on, it would be nice to see an example.

**Comment by xpgupta** [comment]
We have custom validations like maxLength check, special characters check, required field check , which are set to be validate on "OnBlur" event, but while i apply this trim directive, only trim works and no other prior validations work.

**Comment by anein** [comment]
Please, forgive me, I'm not professor Albus Dumbledore, and my personal prophets are on holiday, thus I cannot predict what is going on in your custom validators. The directive works well with in-built validators. Here is the [demo](https://anein.github.io/angular2-trim-directive/).

**Comment by chrisnassouri** [comment]
Opening this back up because I've ran into this as well. It seems that in a template driven form, such as the following...

`<input
                            type="text"
                            class="form-control input-lg"
                            id="firstName"
                            required
                            minlength="2"
                            maxlength="50"
                            [(ngModel)]="model.firstName"
                            pattern="^[a-zA-Z_`'\-\.]+(?! and )( [a-zA-Z_`'\-\.]+)*$"
                            name="firstName"
                            #firstName="ngModel"
                            aria-required="true"
                            [attr.aria-invalid]="!!firstName.errors"
                            nospace>

                    <div *ngIf="firstName.errors && (firstName.touched) || firstName.errors && invalid" class="text-danger error">
                        <div *ngIf="firstName.errors.minlength">Cannot be less than 2 characters.</div>
                        <div *ngIf="firstName.errors.required">Please enter your first name.</div>
                        <div *ngIf="firstName.errors.pattern">Please enter only letters, apostrophes, hyphens and periods.</div>
                    </div>`

The "touched" validation does not trigger but when removing the validation, it does work as intended. @anein
