### ISSUE TITLE
2.1.1 is not working

### ISSUE THREAD

**Issue by pfeigl** [anein/angular2-trim-directive#11]
With version 2.1.1 there is no longer the required files in the dist folder of the package. Thus the import is not working any longer. See this error:

ERROR in .....ts(8,33): error TS2307: Cannot find module 'ng2-trim-directive'.

Everything seems to be placed into a dist/src folder now and there is also an additional dist/node_modules folder which is probably not wanted.

With 2.1.0 the package structure seems to be still ok.

**Comment by anein** [comment]
Thank you for pointing out the issue. 
 
Now, `ngc` requires to set the root path clearly. My bad. Update to 2.1.2.
