### ISSUE TITLE
error with angular 4.4

### ISSUE THREAD

**Issue by naivefun** [anein/angular2-trim-directive#12]
```
Angular compilation done, starting webpack bundling.
Error: Metadata version mismatch for module ~/Documents/GitHub/webapp/node_modules/ng2-trim-directive/dist/input-trim.directive.d.ts, found version 4, expected 3
```

**Comment by anein** [comment]
Hi there!

The latest version(2.1.2) of the directive was compiled using angular 5, that causes the problem for the AOT compilation. If you prefer to use it with angular 4, simply downgrade the directive to 2.1.0.
