### ISSUE TITLE
preventing validation from firing

### ISSUE THREAD

**Issue by chrisnassouri** [anein/angular2-trim-directive#14]
It seems that in a template driven form, such as the following...

`<input type="text" class="form-control input-lg" id="firstName" required minlength="2" maxlength="50" [(ngModel)]="model.firstName" name="firstName" #firstName="ngModel" aria-required="true" [attr.aria-invalid]="!!firstName.errors" trim>`

`<div *ngIf="firstName.errors && (firstName.touched) class="text-danger error">`
`<div *ngIf="firstName.errors.minlength">Cannot be less than 2 characters.</div>`
`<div *ngIf="firstName.errors.required">Please enter your first name.</div>`
`</div>`

The "touched" validation does not trigger but when removing the directive, it does work as intended. Oddly enough, switching it to dirty acts as touched at that point. @anein

**Comment by anein** [comment]
Hello there!

Do you have any suggestions for solving the problem? What if we add the "touch" HostListener?

**Comment by chrisnassouri** [comment]
Hey @anein, I'm trying to figure out why this is happening myself - I haven't been able to figure it out totally. But as far as I know, touch is actually just an alias for blur (correct me if I'm wrong but that's my understanding). So either it's trying to trigger multiple events and prioritizes the directive over the validation, or there's an issue with modifying the value after the state change. Considering it does it on blur, the value is programmatically modified once you're out of the field. 

All this is hypothetical but I'd imagine it has to do something with the validator trying to validate the original value during the time the field is cleared to make way for the new trimmed value (it's inserting the new value after the validator is "touched"). What's the most interesting is that if you track the state of the field, the state does properly read valid or invalid but displaying messaging based on the  *ngIf="firstName.errors && (firstName.touched) fails. 

I've "resolved" this by changing validation in the template to dirty, and even though I originally thought it was weird, it actually makes some sense. That's because dirty real time validates as the user is changing the value, so if you're programmatically updating the value in the field it'll live validate when inserting, unlike touched which only does it when you click outside of the field.

In my time using Angular, I've also seen an issue with autofill in Chrome which produces similar behavior. Basically, Chrome autofill programmatically inserts the value of a field AFTER the state has changed which prevents validation from clearing. 

This produces a situation in which a user would cannot submit a form unless they went back and clicked into the fields. Now I know this is an entirely different issue than what we're seeing here but the point being is that Angular does have issues with determining state when values are modified.

**Comment by anein** [comment]
Thank you for your commit. The solution was really simple. 🙂👍
