### ISSUE TITLE
puts "undefined" in empty inputs

### ISSUE THREAD

**Issue by pgossmann** [anein/angular2-trim-directive#18]
the trim  directive does not work well when the model is undefined.
then it converts undefined to a string "undefined" 
so the text input is filled with "undefined" instead of being empty

**Comment by ShinDarth** [comment]
@anein I'm using version `2.1.7` and I still have this problem.

More specifically, if the value is `null` then it's ok, if it's `undefined` then the `"undefined"` string appears.

**Comment by anein** [comment]
It's odd that, for some reason, this [`val = val || ''`](https://github.com/anein/angular2-trim-directive/blob/46a8181c1e55fe95598a6b452f9c33e588bd6f34/src/input-trim.directive.ts#L70) condition passes "undefined" values. The demo has a field with [`undefined value`](https://github.com/anein/angular2-trim-directive/blob/46a8181c1e55fe95598a6b452f9c33e588bd6f34/example/src/app/app.component.ts#L26) and it works fine. 

So,  we have no choice but to rewrite this condition. =)

**Comment by ShinDarth** [comment]
@anein any news on this? it looks quite a serious issue and it's currently breaking our production env

**Comment by anein** [comment]
@ShinDarth Yes, but to be sure that all works fine, could you post an example how you got the issue?

**Comment by ShinDarth** [comment]
@anein sure, here it is:

https://stackblitz.com/edit/angular-vobpkx

**Comment by anein** [comment]
@ShinDarth Thank you. I thought you use a template-driven form. The issue comes in a reactive form for the reason that you forcefully set `undefined` on the `onInit` step. Originally, the reactive form automatically converts all `undefined` values to null during initialization to avoid this issue.

The repo will be updated soon. 😉

**Comment by ShinDarth** [comment]
@anein please check my PR https://github.com/anein/angular2-trim-directive/pull/29
