### ISSUE TITLE
It gives state as invalid for single character

### ISSUE THREAD

**Issue by AyushG25** [anein/angular2-trim-directive#22]

**Comment by jassiwalia001** [comment]
comment these lines and your code will be working 
//if (!this._value) {
    //   this._value = value;
    // }

**Comment by anein** [comment]
And no one makes a PR. =D

**Comment by dannoh** [comment]
I started to, but frankly I don't have the Angular knowledge.  It's not as simple as removing the line, it was put there to stop fields becoming dirty by just tabbing through them.

**Comment by anein** [comment]
I understand. That makes me think that E2E tests should be added.
