### ISSUE TITLE
white space between statement

### ISSUE THREAD

**Issue by LimarenkoDenis** [anein/angular2-trim-directive#24]
Hi, I am wondering if I there some configuration for allowing whitespace between string, I just want to trim whitespace before and after some user's input, 
I understand that we can't determinate if it is space between, but probably on some 'onblur' event trim last whitespaces

**Comment by anein** [comment]
Привет!
Разве она этого не делает на blur event? Или ты про то, чтобы оставлять только по одному пробелу после каждого слова: `слово__слово_` => `слово_слово?`
