### ISSUE TITLE
Copy pasting doesn't trigger change event in v2.1.5

### ISSUE THREAD

**Issue by juhosuominen** [anein/angular2-trim-directive#26]
Pasting something into an input field with "trim" doesn't trigger `control.valueChanges`. This prevents validators from running and the form content isn't updated with the copy pasted data. This issue is present on the demo page. v2.1.4 works normally.

**Comment by chetan-northout** [comment]
Same bug

**Comment by irinelpascu** [comment]
Why has this been closed without fix?
