### ISSUE TITLE
Doesn't work with es6

### ISSUE THREAD

**Issue by ShinDarth** [anein/angular2-trim-directive#28]
If I set `"target": "es6"` in my tsconfig, whenever I use the `[trim]` directive I get the following error:

> TypeError: Class constructor DefaultValueAccessor cannot be invoked without 'new'

**Comment by ShinDarth** [comment]
@anein is there a way I can try to install the project locally, try to fix the bug, then package it and import it to my app? because I cannot reproduce this bug locally. It only appears when I install the library via npm

**Comment by anein** [comment]
Are you trying to build an es5 directive using "es6" target ? 😉

**Comment by ShinDarth** [comment]
@anein why shouldn't this directive work with es6? can you give me more context? I would like to understand more. I've also tried to include the directive file inside my project and compile it with es6 and it works fine.

**Comment by shakalya195** [comment]
use ng-trim-ignore class in each input field in case of using ng-trim-value-accessor library
