### ISSUE TITLE
Trim directive is breaking the disabled state of controls

### ISSUE THREAD

**Issue by ShinDarth** [anein/angular2-trim-directive#32]
Trim directive version: 2.2.1
Reproduction: https://stackblitz.com/edit/angular-v5pu3v

As you can see in my reproduction, I have two disabled fields. The one using the `[trim]="'blur'"` directive does not appear disabled when it should.

**Comment by anein** [comment]
Because `setDisabledState` isn't implemented. ¯\_(ツ)_/¯

**Comment by ShinDarth** [comment]
@anein yes, please check my PR https://github.com/anein/angular2-trim-directive/pull/33 :dancer:
