### ISSUE TITLE
throw error when enter 1 letter only. with trim="blur" in reactive form

### ISSUE THREAD

**Issue by zymr-keshav** [anein/angular2-trim-directive#35]
angular v 6.1.10
ng2-trim-directive v 2.3.0

using in reactive form with **trim="blur"** options
it works fine as expected

1. trim input after **blur** 
1. trim if all whitespace and also display error on the required field.

BUT facing one strange issue. when user input only a single letter, it throws the same error as required.

interestingly it works fine when writing 2 letters and removes the later from the input box.

Will you please check this issue?

check [this demo](https://stackblitz.com/edit/angular6-setup-zpsjpa?file=src%2Fapp%2Fapp.component.html) . enter 'a' and then enter `aa` and remove the `a` 

why both are behaving differently?

**Comment by anein** [comment]
Hey!

Yep. Weird behavior. I think it's safe to assume that the issue lies in line  [129](https://github.com/anein/angular2-trim-directive/blob/58f14e7752f34fb130ced2f0b7e9d2a05248ac12/src/input-trim.directive.ts#L129), causing the model isn't updated.

**Comment by zymr-keshav** [comment]
yes, the issue possibly on line number 129 and how to fix that?
I have tried to create pull request but failed and also git clone but it failed due to typescript version mismatch.

**Comment by zymr-keshav** [comment]
this code changes fixed my issue but do not know whether it is applicable to all or not. One thing i did not understand is when we assign `const previousValue = this._value;` then  how these `const trimmedValue = this._value.trim();` and `previous.trim()` can be different?

```
 private updateValue(event: string, value: string): void {
        // check if the user has set an optional attribute.
        const currentValue = this.trim !== '' && event !== this.trim ? value : value.trim();

        const previousValue = this._value;

        this.writeValue(currentValue);

        const trimmedValue = this._value.trim();
        console.log({ trimmedValue });
        if (trimmedValue !== previousValue && (trimmedValue !== '' || previousValue.trim() !== '')) {
            this.onChange(this._value);
        }
    }
```

**Comment by alexvisenze** [comment]
Pasting is also broken again :(

**Comment by anein** [comment]
THAT condition, which is responsible for updating the model, wasn't optimized. Done and done. =)
