### ISSUE TITLE
Safari: cursor moves to the end if you type the symbol at the beginning/middle

### ISSUE THREAD

**Issue by AlexeyBogdan95** [anein/angular2-trim-directive#36]
In Safari, if you type the symbol at the beginning/middle a cursor usually moves to the end

**Comment by AlexeyBogdan95** [comment]
@anein Actually, I have a branch which contains a fix for this issue, but I can't push it to origin. How can I do it? Thank you!

**Comment by anein** [comment]
@AlexeyBogdan95 Как обычно. =)  https://help.github.com/articles/about-pull-requests/

**Comment by AlexeyBogdan95** [comment]
@anein https://github.com/anein/angular2-trim-directive/pull/37

**Comment by anein** [comment]
For some reason the solution doesn't pass the tests. =\

**Comment by Hyuchiha** [comment]
I make a pull request with an improvement of your fix, it passes the test now

**Comment by anein** [comment]
@Hyuchiha  Done and done! Thank you for fixing this old bag. 👍
