### ISSUE TITLE
Breaking change from 2.3.0 to 2.3.1

### ISSUE THREAD

**Issue by FrancescoBorzi** [anein/angular2-trim-directive#39]
In my app I have a Form with a Control that has 2 validators:

- Required (to make sure that the field is not empty)
- Pattern (a regular expression that makes sure that the field is a valid URL)

A text error "Required" or "Pattern" is displayed according to what error is there.

Unfortunately, the version `2.3.1` changes the behaviour and this shouldn't happen since it's not a major release.

To reproduce the same scenario with different trim-directive versions:

- SCENARIO USING `2.3.0`: https://stackblitz.com/edit/angular-se8hgt
- SCENARIO USING `2.3.1`: https://stackblitz.com/edit/angular-czfmbx

HOW TO REPRODUCE THE DIFFERENCE:

- Initially the field is empty and the error "Required" is displayed
- Type some random text in the field, since it's not a valid URL, the error "Pattern" is displayed
- Delete the text

At this point, using version `2.3.0` will correctly display "Required" since the field is now empty, however the scenario that uses version `2.3.1` will keep displaying "Pattern", which is wrong.

**Comment by anein** [comment]
Oh, got the problem - the model is not erased completely. 😅

**Comment by FrancescoBorzi** [comment]
Version `2.3.2` solves this problem. Thanks a lot @anein !
