### ISSUE TITLE
doesn't work with input type="email"

### ISSUE THREAD

**Issue by xpgupta** [anein/angular2-trim-directive#9]
trim directive doesn't work with input type="email",. working fine with type="text".

**Comment by anein** [comment]
DefaultValueAccessor uses `setProperty` for updating value of an input element, and for some reason, it doesn't work with HTML 5 input elements. Calling additional `setAttribute` in the `writeValue` method solves this problem. Check the [Demo](https://anein.github.io/angular2-trim-directive/) page.
